/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-13 08:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.man;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class baiduAPI_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body, html,#allmap {width: 100%;height: 100%;overflow: hidden;margin:0;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://api.map.baidu.com/api?v=2.0&ak=988fe5f90a25d9f9c4c08054d1daa9a8\"></script>\r\n");
      out.write("<title>Map</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\talert(log);\r\n");
      out.write("\t\t$(\"div#menu ul li\").hover(function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'+=30px'}, 500);\r\n");
      out.write("\t\t}, function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'-=30px'},500);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- BackGround -->\r\n");
      out.write("    <div  style=\"width:100%;height:100%;position:fixed;z-index:-1;top:0px;left:0px;\">\r\n");
      out.write("\t\t<img src=\"../bgp.jpg\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("\t</div> \r\n");
      out.write("    <!-- *********  Header  ********** -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"header_in\">\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"menu\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a href=\"../man/index.jsp\" class=\"active\">Home</a></li>\r\n");
      out.write("            <li><a href=\"../man/info.jsp\">Information</a></li>\r\n");
      out.write("            <li><a href=\"../man/record.jsp\">Record</a></li>\r\n");
      out.write("            <li><a href=\"../man/show.jsp\" >Show</a></li>            \r\n");
      out.write("         </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"context\">\r\n");
      out.write("    \t<img src=\"img/bgimg.jpg\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"allmap\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("// ç¾åº¦å°å¾APIåè½\r\n");
      out.write("var map = new BMap.Map(\"allmap\");\r\n");
      out.write("var point = new BMap.Point(116.404, 39.915);\r\n");
      out.write("map.centerAndZoom(point,15);\r\n");
      out.write("var contextMenu = new BMap.ContextMenu();\r\n");
      out.write("var txtMenuItem = [\r\n");
      out.write("  {\r\n");
      out.write("   text:'æ¾å¤§',\r\n");
      out.write("   callback:function(){map.zoomIn()}\r\n");
      out.write("  },\r\n");
      out.write("  {\r\n");
      out.write("   text:'ç¼©å°',\r\n");
      out.write("   callback:function(){map.zoomOut()}\r\n");
      out.write("  },\r\n");
      out.write("  {\r\n");
      out.write("   text:'æ¾ç½®å°æå¤§çº§',\r\n");
      out.write("   callback:function(){map.setZoom(18)}\r\n");
      out.write("  },\r\n");
      out.write("  {\r\n");
      out.write("   text:'æ¥çå¨å½',\r\n");
      out.write("   callback:function(){map.setZoom(4)}\r\n");
      out.write("  },\r\n");
      out.write("  {\r\n");
      out.write("   text:'å¨æ­¤æ·»å æ æ³¨',\r\n");
      out.write("   callback:function(p){\r\n");
      out.write("    var marker = new BMap.Marker(p), px = map.pointToPixel(p);\r\n");
      out.write("    map.addOverlay(marker);\r\n");
      out.write("   }\r\n");
      out.write("  }\r\n");
      out.write(" ];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" for(var i=0; i < txtMenuItem.length; i++){\r\n");
      out.write("  contextMenu.addItem(new BMap.MenuItem(txtMenuItem[i].text,txtMenuItem[i].callback,100));\r\n");
      out.write("  if(i==1 || i==3) {\r\n");
      out.write("   contextMenu.addSeparator();\r\n");
      out.write("  }\r\n");
      out.write(" }\r\n");
      out.write(" map.addContextMenu(contextMenu);\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
