/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-19 07:07:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.man;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class googleAPI_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("    <title>Map</title>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\" />\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\t#menu {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: -20px;\r\n");
      out.write("\tfont-size: 115%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li {\r\n");
      out.write("\t/*float: left;*/\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #101115;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 29px 40px 0 40px;\r\n");
      out.write("\theight: 46px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tfilter:alpha(opacity=50); \r\n");
      out.write("\t-moz-opacity:0.5; \r\n");
      out.write("\topacity:0.5;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a:hover {\r\n");
      out.write("\tbackground-color: #f3f3f3;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a.active {\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tcolor: rgb(200,200,245);\r\n");
      out.write("\tfilter:alpha(opacity=90); \r\n");
      out.write("\t-moz-opacity:0.9; \r\n");
      out.write("\topacity:0.9;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #context {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: 300px;\r\n");
      out.write("\tbuttom: 200px;\r\n");
      out.write("\tright: 100px;\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      html { height: 100% }\r\n");
      out.write("      body { height: 100%; margin: 0; padding: 0 }\r\n");
      out.write("      #map_canvas {\r\n");
      out.write("\t\ttop: 75px;\r\n");
      out.write("\t\tleft: 275px;\r\n");
      out.write("\t\tbuttom: 200px;\r\n");
      out.write("\t\tright: 100px;\r\n");
      out.write("      \theight: 65%;\r\n");
      out.write("      \twidth: 50%;\r\n");
      out.write("      \t\r\n");
      out.write("      \t border:1px solid #5d81ab; \r\n");
      out.write("\t    -webkit-box-shadow:0px 1px 1px rgba(255,255,255,0.2) inset, 1px 1px 3px rgba(0,0,0,0.2), 0px 0px 0px 4px rgba(188,188,188,0.5);\r\n");
      out.write("\t    -moz-box-shadow:0px 1px 1px rgba(255,255,255,0.2) inset, 1px 1px 3px rgba(0,0,0,0.2), 0px 0px 0px 4px rgba(188,188,188,0.5);\r\n");
      out.write("\t    box-shadow:0px 1px 1px rgba(255,255,255,0.2) inset, 1px 1px 3px rgba(0,0,0,0.2), 0px 0px 0px 4px rgba(188,188,188,0.5);\r\n");
      out.write("\t    -webkit-border-radius:20px;\r\n");
      out.write("\t    -moz-border-radius:20px;\r\n");
      out.write("\t    border-radius:10px;\r\n");
      out.write("      \t\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("\t#sub-title {\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook',Georgia, 'New York', serif;\r\n");
      out.write("\t    font-weight: 200;\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t \t width: auto;\r\n");
      out.write("\t  \tfloat:left;\r\n");
      out.write("\t  \tmargin: 0 auto;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    padding: 10px 40px 10px 20px ;\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: #222; \r\n");
      out.write("\t    border-radius: 0.4em;\r\n");
      out.write("\t    border: 1px solid #191919;\r\n");
      out.write("\t    box-shadow: \r\n");
      out.write("\t        inset 0 0 2px 1px rgba(255,255,255,0.08), \r\n");
      out.write("\t        0 16px 10px -8px rgba(0, 0, 0, 0.6);\r\n");
      out.write("\t        \r\n");
      out.write("\t    /*font*/\r\n");
      out.write("\t    \r\n");
      out.write("\t    color: #ddd;\r\n");
      out.write("\t    font-size: 25px;\r\n");
      out.write("\t    letter-spacing: 1px;\r\n");
      out.write("\t    text-shadow: 0 1px 0 #000;\r\n");
      out.write("\t    text-indent: 10px;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#sub-title label {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    width: 40%;\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    padding-top: 9px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    color: #ddd;\r\n");
      out.write("\t    font-size: 12px;\r\n");
      out.write("\t    text-transform: uppercase;\r\n");
      out.write("\t    letter-spacing: 1px;\r\n");
      out.write("\t    text-shadow: 0 1px 0 #000;\r\n");
      out.write("\t    text-indent: 10px;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t    cursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#sub-title:after {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content: \"\";\r\n");
      out.write("\t    height: 1px;\r\n");
      out.write("\t    width: 33%;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 20%;\r\n");
      out.write("\t    top: 0;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: -moz-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -ms-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -o-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -webkit-gradient(linear, 0 0, 100% 0, from(transparent), color-stop(0.25, #444), color-stop(0.5, #b6b6b8), color-stop(0.75, #444), to(transparent));\r\n");
      out.write("\t    background: -webkit-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#sub-title:before {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content: \"\";\r\n");
      out.write("\t    width: 8px;\r\n");
      out.write("\t    height: 5px;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 34%;\r\n");
      out.write("\t    top: -7px;\r\n");
      out.write("\t    \r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    border-radius: 50%;\r\n");
      out.write("\t    box-shadow: 0 0 6px 4px #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("      src=\"http://maps.googleapis.com/maps/api/js?key=AIzaSyDEFUdRQuTsJcVy8MRYrYwUwiGryjyBylk&sensor=false\">\r\n");
      out.write("    </script>\r\n");
      out.write("   <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      function initialize() {\r\n");
      out.write("        var mapOptions = {\r\n");
      out.write("          center: new google.maps.LatLng(39.990168, 116.295304),\r\n");
      out.write("          zoom: 12,\r\n");
      out.write("          mapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("        };\r\n");
      out.write("        var map = new google.maps.Map(document.getElementById(\"map_canvas\"),\r\n");
      out.write("            mapOptions);\r\n");
      out.write("\r\n");
      out.write("        map.addControl(new GLargeMapControl());\r\n");
      out.write("        map.addControl(new GMapTypeControl());\r\n");
      out.write("        map.enableScrollWheelZoom(); \r\n");
      out.write("        map.setCenter(new GLatLng(39.990168, 116.295304), 10);\r\n");
      out.write("        map.enableDoubleClickZoom(); \r\n");
      out.write("        map.enableScrollWheelZoom();\r\n");
      out.write("        \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("  \t$(document).ready(function(){\r\n");
      out.write("  \t\t//CreateTable(\"div#context\");\r\n");
      out.write("  \t\t//CreateUserInfoTable(\"div#context\");\r\n");
      out.write("  \t\t$(\"div#menu ul li\").hover(function(){\r\n");
      out.write("  \t\t\t$(this).animate({left:'+=25px'}, 500);\r\n");
      out.write("  \t\t}, function(){\r\n");
      out.write("  \t\t\t$(this).animate({left:'-=25px'},500);\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t\t$(\"#sub-title\").hide().show(300);\r\n");
      out.write("  \t});\r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body onload=\"initialize()\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"map_canvas\" ></div>\r\n");
      out.write("        \r\n");
      out.write("    <!-- BackGround -->\r\n");
      out.write("    <div  style=\"width:100%;height:100%;position:fixed;z-index:-1;top:0px;left:0px;\">\r\n");
      out.write("\t\t<img src=\"img/bgimg.jpg\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("\t</div> \r\n");
      out.write("    <!-- *********  Header  ********** -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"header_in\">\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"menu\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a href=\"../man/index.jsp\">Home</a></li>\r\n");
      out.write("            <li><a href=\"../man/info.jsp\">Information</a></li>\r\n");
      out.write("            <li><a href=\"../man/record.jsp\">Record</a></li>\r\n");
      out.write("            <li><a href=\"../man/show.jsp\" >Show</a></li>            \r\n");
      out.write("         </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    <div id=\"context\">\r\n");
      out.write("    \t<div id=\"sub-title\">\r\n");
      out.write("    \t\tYour Track\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
