/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-13 07:11:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.man;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class InfoUpdateError_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"refresh\" content=\"3;url=../man/info.jsp\">\r\n");
      out.write("    <title>Information</title>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t#menu {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: -20px;\r\n");
      out.write("\tfont-size: 115%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li {\r\n");
      out.write("\t/*float: left;*/\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #101115;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 29px 40px 0 40px;\r\n");
      out.write("\theight: 46px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tfilter:alpha(opacity=50); \r\n");
      out.write("\t-moz-opacity:0.5; \r\n");
      out.write("\topacity:0.5;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a:hover {\r\n");
      out.write("\tbackground-color: #f3f3f3;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a.active {\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tcolor: rgb(200,200,245);\r\n");
      out.write("\tfilter:alpha(opacity=90); \r\n");
      out.write("\t-moz-opacity:0.9; \r\n");
      out.write("\topacity:0.9;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #context {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: 250px;\r\n");
      out.write("\tbuttom: 200px;\r\n");
      out.write("\tright: 100px;\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #gravatar{\r\n");
      out.write("\t\tfont-family:Georgia, serif;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: 50px;\r\n");
      out.write("\t\tleft: 700px;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tfont-size: 100%;\r\n");
      out.write("\t\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\t\tmargin-right: 0px;\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tborder-style: solid;\r\n");
      out.write(" \t\tborder-color: rgba(255,255,255,0.35);\r\n");
      out.write("  \t\tborder-width: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t#tips{\r\n");
      out.write("\t    background: rgba(220,220,255,0.35);\r\n");
      out.write("\t   \r\n");
      out.write("\t    padding-left:40px;\r\n");
      out.write("\t    padding-right:40px;\r\n");
      out.write("\t    padding-top:0px;\r\n");
      out.write("\t    padding-button:50px;\r\n");
      out.write("\t    height:auto;\r\n");
      out.write("\t    display:inline-block;\r\n");
      out.write("\t    position:relative;\r\n");
      out.write("\t    top:200px;\r\n");
      out.write("\t    \r\n");
      out.write("\t    border:1px solid #5d81ab; \r\n");
      out.write("\t    -webkit-box-shadow:0px 1px 1px rgba(255,255,255,0.2) inset, 1px 1px 3px rgba(0,0,0,0.2), 0px 0px 0px 4px rgba(188,188,188,0.5);\r\n");
      out.write("\t    -moz-box-shadow:0px 1px 1px rgba(255,255,255,0.2) inset, 1px 1px 3px rgba(0,0,0,0.2), 0px 0px 0px 4px rgba(188,188,188,0.5);\r\n");
      out.write("\t    box-shadow:0px 1px 1px rgba(255,255,255,0.2) inset, 1px 1px 3px rgba(0,0,0,0.2), 0px 0px 0px 4px rgba(188,188,188,0.5);\r\n");
      out.write("\t    -webkit-border-radius:20px;\r\n");
      out.write("\t    -moz-border-radius:20px;\r\n");
      out.write("\t    border-radius:10px;\r\n");
      out.write("\t    \r\n");
      out.write("\t    clear:both;\r\n");
      out.write("\t    -webkit-transition:all 0.3s linear;\r\n");
      out.write("\t    -moz-transition:all 0.3s linear;\r\n");
      out.write("\t    -o-transition:all 0.3s linear;\r\n");
      out.write("\t    transition:all 0.3s linear;\r\n");
      out.write("\t}\r\n");
      out.write("\t#tips #word{\r\n");
      out.write("\t    position:relative;\r\n");
      out.write("\t    padding-top:0px;\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    font-size:55px;\r\n");
      out.write("\t    font-weight:600;\r\n");
      out.write("\t    white-space:nowrap;\r\n");
      out.write("\t    text-shadow:0px 1px 1px rgba(255,255,255,0.3);\r\n");
      out.write("\t    color:#fff;\r\n");
      out.write("\t    -webkit-transition:all 0.2s linear;\r\n");
      out.write("\t    -moz-transition:all 0.2s linear;\r\n");
      out.write("\t    -o-transition:all 0.2s linear;\r\n");
      out.write("\t    transition:all 0.2s linear;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t//CreateTable(\"div#context\");\r\n");
      out.write("\t\t//CreateUserInfoTable(\"div#context\");\r\n");
      out.write("\t\t$(\"#tips\").hide().show(333);\r\n");
      out.write("\t\t$(\"#context\").hide().show(333);\r\n");
      out.write("\t\t$(\"div#menu ul li\").hover(function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'+=25px'}, 500);\r\n");
      out.write("\t\t}, function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'-=25px'},500);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  >\r\n");
      out.write("    \r\n");
      out.write("    <!-- BackGround -->\r\n");
      out.write("    <div  style=\"width:100%;height:100%;position:fixed;z-index:-1;top:0px;left:0px;\">\r\n");
      out.write("\t\t<img src=\"../bgp.jpg\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("\t</div> \r\n");
      out.write("    <!-- *********  Header  ********** -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"header_in\">\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"menu\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a href=\"../man/index.jsp\" class=\"active\">Home</a></li>\r\n");
      out.write("            <li><a href=\"../man/info.jsp\">Information</a></li>\r\n");
      out.write("            <li><a href=\"../man/record.jsp\">Record</a></li>\r\n");
      out.write("            <li><a href=\"../man/show.jsp\" >Show</a></li>          \r\n");
      out.write("         </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"context\" class = \"info\" style=\"top:0px;right:250px;\">\r\n");
      out.write("   \t\t <div id=\"tips\">\r\n");
      out.write("    \t\t<p id = \"word\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /man/InfoUpdateError.jsp(179,4) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("message");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
