/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-19 07:09:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.man;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.UserInfo;
import com.UserInfoUtil;
import com.man.UserInfoShowDAO;

public final class infoUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.release();
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Information</title>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t#menu {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: -20px;\r\n");
      out.write("\tfont-size: 115%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li {\r\n");
      out.write("\t/*float: left;*/\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #101115;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 29px 40px 0 40px;\r\n");
      out.write("\theight: 46px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tfilter:alpha(opacity=50); \r\n");
      out.write("\t-moz-opacity:0.5; \r\n");
      out.write("\topacity:0.5;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a:hover {\r\n");
      out.write("\tbackground-color: #f3f3f3;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a.active {\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tcolor: rgb(200,200,245);\r\n");
      out.write("\tfilter:alpha(opacity=90); \r\n");
      out.write("\t-moz-opacity:0.9; \r\n");
      out.write("\topacity:0.9;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #context {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: 300px;\r\n");
      out.write("\tbuttom: 200px;\r\n");
      out.write("\tright: 100px;\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #gravatar{\r\n");
      out.write("\t\tfont-family:Georgia, serif;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: 50px;\r\n");
      out.write("\t\tleft: 700px;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tfont-size: 100%;\r\n");
      out.write("\t\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\t\tmargin-right: 0px;\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tborder-style: solid;\r\n");
      out.write(" \t\tborder-color: rgba(255,255,255,0.35);\r\n");
      out.write("  \t\tborder-width: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\t/*info table------------------------------------------------------------*/\r\n");
      out.write("\t.info-table\r\n");
      out.write("\t{\r\n");
      out.write("\t  width: 500px;\r\n");
      out.write("\t  float:left;\r\n");
      out.write("\t  margin: 0 auto;\r\n");
      out.write("\t  border-collapse: separate;\r\n");
      out.write("\t  border-spacing: 0;\r\n");
      out.write("\t  text-shadow: 0 1px 0 #fff;\r\n");
      out.write("\t  color: rgba(50,50,50,1.0);\r\n");
      out.write("\t  background: rgba(200,200,200,0.8);\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table td\r\n");
      out.write("\t{\r\n");
      out.write("\t  height: 40px;\r\n");
      out.write("\t  line-height: 40px;\r\n");
      out.write("\t  padding: 0 20px;\r\n");
      out.write("\t  border-bottom: 1px solid #cdcdcd;\r\n");
      out.write("\t  box-shadow: 0 1px 0 white;\r\n");
      out.write("\t  -moz-box-shadow: 0 1px 0 white;\r\n");
      out.write("\t  -webkit-box-shadow: 0 1px 0 white;\r\n");
      out.write("\t  white-space: nowrap;\r\n");
      out.write("\t  text-align: center;\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*Body*/\r\n");
      out.write("\t.info-table tbody td\r\n");
      out.write("\t{\r\n");
      out.write("\t  text-align: center;\r\n");
      out.write("\t  font: normal 20px Georgia , Verdana, Arial, Helvetica;\r\n");
      out.write("\t  width: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table td:nth-child(1)\r\n");
      out.write("\t{\r\n");
      out.write("\t  background: rgba(150,150,150,0);\r\n");
      out.write("\t  width: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table td:nth-child(2)\r\n");
      out.write("\t{\r\n");
      out.write("\t  background: #e7f3d4;\r\n");
      out.write("\t  background: rgba(225,225,225,0.35);\r\n");
      out.write("\t  width: 150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table tr:nth-child(even){\r\n");
      out.write("\t  \tbackground: rgba(255,220,220,0.5);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table tr:nth-child(odd){\r\n");
      out.write("\t  \tbackground: rgba(220,220,255,0.5);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table tr:hover\r\n");
      out.write("\t{\r\n");
      out.write("\t  background: rgba(255,255,255,0.3);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* manage button ----------------------------------------------------------------------*/\r\n");
      out.write("    .info #manage input[type=button] {\r\n");
      out.write("    /* Width and position */\r\n");
      out.write("    width: 140px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    padding: 4px 2px;\r\n");
      out.write("    margin: 5px 20px 0px 20px ;\r\n");
      out.write("    \r\n");
      out.write("    /* Styles */\r\n");
      out.write("    border: 1px solid #0273dd; /* Fallback */\r\n");
      out.write("    border: 1px solid rgba(0,0,0,0.4);\r\n");
      out.write("    box-shadow:\r\n");
      out.write("        inset 0 1px 0 rgba(255,255,255,0.3),\r\n");
      out.write("        inset 0 10px 10px rgba(255,255,255,0.1);\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    background: rgba(100,100,255,0.5);\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("  \r\n");
      out.write("    /* Font styles */\r\n");
      out.write("    font-family: 'trebuchet MS', 'Lucida Sans', Arial;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: 200;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    text-shadow: 0 -1px 0 rgba(100,100,100,0.5);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info #manage input[type=button]:hover { \r\n");
      out.write("\t    box-shadow: inset 0 1px 0 rgba(255,255,255,0.6);\r\n");
      out.write("\t}\r\n");
      out.write("\t/* end manage button ---------------------------------------------------------*/   \r\n");
      out.write("\t#form-info {\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook',Georgia, 'New York', serif;\r\n");
      out.write("\t    font-weight: 200;\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t \t width: 500px;\r\n");
      out.write("\t  \tfloat:left;\r\n");
      out.write("\t  \tmargin: 0 auto;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    padding: 10px;\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: #222; \r\n");
      out.write("\t    border-radius: 0.4em;\r\n");
      out.write("\t    border: 1px solid #191919;\r\n");
      out.write("\t    box-shadow: \r\n");
      out.write("\t        inset 0 0 2px 1px rgba(255,255,255,0.08), \r\n");
      out.write("\t        0 16px 10px -8px rgba(0, 0, 0, 0.6);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info label {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    width: 40%;\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    padding-top: 9px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    color: #ddd;\r\n");
      out.write("\t    font-size: 12px;\r\n");
      out.write("\t    text-transform: uppercase;\r\n");
      out.write("\t    letter-spacing: 1px;\r\n");
      out.write("\t    text-shadow: 0 1px 0 #000;\r\n");
      out.write("\t    text-indent: 10px;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t    cursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info input[type=text],\r\n");
      out.write("\t#form-info input[type=password] {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    width: 50%;\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    padding: 8px 5px;\r\n");
      out.write("\t    margin-bottom: 10px;\r\n");
      out.write("\t    font-size: 12px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: #1f2124; /* Fallback */\r\n");
      out.write("\t    background: -moz-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: -ms-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: -o-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: -webkit-gradient(linear, 0 0, 0 100%, from(#1f2124), to(#27292c));\r\n");
      out.write("\t    background: -webkit-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: linear-gradient(#1f2124, #27292c);    \r\n");
      out.write("\t    border: 1px solid #000;\r\n");
      out.write("\t    box-shadow:\r\n");
      out.write("\t        0 1px 0 rgba(255,255,255,0.1);\r\n");
      out.write("\t    border-radius: 3px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Font styles */\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook',Georgia, 'New York', serif;\r\n");
      out.write("\t    color: #fff;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info input[type=text]:hover,\r\n");
      out.write("\t#form-info input[type=password]:hover {\r\n");
      out.write("\t    background: #27292c;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info input[type=text]:focus, \r\n");
      out.write("\t#form-info input[type=password]:focus {\r\n");
      out.write("\t    box-shadow: inset 0 0 2px #000;\r\n");
      out.write("\t    background: #494d54;\r\n");
      out.write("\t    border-color: #51cbee;\r\n");
      out.write("\t    outline: none; /* Remove Chrome outline */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*#form-info p:nth-child(3),\r\n");
      out.write("\t#form-info p:nth-child(4) {\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    width: 200px;\r\n");
      out.write("\t}*/\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info label[for=remember] {\r\n");
      out.write("\t    width: auto;\r\n");
      out.write("\t    float: none;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    text-transform: capitalize;\r\n");
      out.write("\t    font-size: 11px;\r\n");
      out.write("\t    font-weight: 400;\r\n");
      out.write("\t    letter-spacing: 0px;\r\n");
      out.write("\t    text-indent: 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info input[type=checkbox] {\r\n");
      out.write("\t    margin-left: 10px;\r\n");
      out.write("\t    vertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info input[type=submit] {\r\n");
      out.write("\t    /* Width and position */\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height:50px;\r\n");
      out.write("\t    padding: 8px 5px;\r\n");
      out.write("\t    float:right;\r\n");
      out.write("\t    margin:0px auto;\r\n");
      out.write("\t  \r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    border: 1px solid #0273dd; /* Fallback */\r\n");
      out.write("\t    border: 1px solid rgba(0,0,0,0.4);\r\n");
      out.write("\t    box-shadow:\r\n");
      out.write("\t        inset 0 1px 0 rgba(255,255,255,0.3),\r\n");
      out.write("\t        inset 0 10px 10px rgba(255,255,255,0.1);\r\n");
      out.write("\t    border-radius: 3px;\r\n");
      out.write("\t    background: #38a6f0;\r\n");
      out.write("\t    cursor:pointer;\r\n");
      out.write("\t  \r\n");
      out.write("\t    /* Font styles */\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook', Georgia, 'New York', serif;\r\n");
      out.write("\t    color: white;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t    font-size: 15px;\r\n");
      out.write("\t    text-shadow: 0 -1px 0 rgba(0,0,0,0.8);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info input[type=submit]:hover { \r\n");
      out.write("\t    box-shadow: inset 0 1px 0 rgba(255,255,255,0.6);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info input[type=submit]:active { \r\n");
      out.write("\t    background: #287db5;\r\n");
      out.write("\t    box-shadow: inset 0 0 3px rgba(0,0,0,0.6);\r\n");
      out.write("\t    border-color: #000; /* Fallback */\r\n");
      out.write("\t    border-color: rgba(0,0,0,0.9);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.no-boxshadow #form-info input[type=submit]:hover {\r\n");
      out.write("\t    background: #2a92d8;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info:after {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content: \"\";\r\n");
      out.write("\t    height: 1px;\r\n");
      out.write("\t    width: 33%;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 20%;\r\n");
      out.write("\t    top: 0;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: -moz-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -ms-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -o-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -webkit-gradient(linear, 0 0, 100% 0, from(transparent), color-stop(0.25, #444), color-stop(0.5, #b6b6b8), color-stop(0.75, #444), to(transparent));\r\n");
      out.write("\t    background: -webkit-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info:before {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content: \"\";\r\n");
      out.write("\t    width: 8px;\r\n");
      out.write("\t    height: 5px;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 34%;\r\n");
      out.write("\t    top: -7px;\r\n");
      out.write("\t    \r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    border-radius: 50%;\r\n");
      out.write("\t    box-shadow: 0 0 6px 4px #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-info p:nth-child(1):before{\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content:\"\";\r\n");
      out.write("\t    width:250px;\r\n");
      out.write("\t    height:100px;\r\n");
      out.write("\t    position:absolute;\r\n");
      out.write("\t    top:0;\r\n");
      out.write("\t    left:45px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    -webkit-transform: rotate(75deg);\r\n");
      out.write("\t    -moz-transform: rotate(75deg);\r\n");
      out.write("\t    -ms-transform: rotate(75deg);\r\n");
      out.write("\t    -o-transform: rotate(75deg);\r\n");
      out.write("\t    transform: rotate(75deg);\r\n");
      out.write("\t    background: -moz-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: -ms-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: -o-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: -webkit-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    pointer-events:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

		String userName = (String)session.getAttribute("USER_NAME");
		if ( userName == null || userName == "" )
		{
			
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\twindow.location.href=\"../login/Error.jsp\"; \r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t");
 
		}
		UserInfoUtil userInfoUtil = new UserInfoUtil();
		UserInfo userInfo = userInfoUtil.getUserInfo(userName);
		UserInfoShowDAO userInfoShowDAO = new UserInfoShowDAO();
		userInfoShowDAO.setUserInfo(userInfo);
		String head ="";
		String content="";
		while( userInfoShowDAO.hasNext()){
			head += userInfoShowDAO.getHead()+"#";
			content += userInfoShowDAO.getContent()+"#";
		}
		
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction CreateTable(div)\r\n");
      out.write("\t  { \r\n");
      out.write("\t   var table=$(\"<table class = \\\"info-table\\\">\");\r\n");
      out.write("\t     table.appendTo($(div));\r\n");
      out.write("\t     var infos = ['Name','Email','Tel','Address','Birthday'];\r\n");
      out.write("\t     var infoNum = 5;\r\n");
      out.write("\t     var aniTime = 300;\r\n");
      out.write("\t     \r\n");
      out.write("\t     var headAll = \"");
      out.print(head);
      out.write("\";\r\n");
      out.write("\t\t var contentAll = \"");
      out.print(content);
      out.write("\";\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var heads = new Array();\r\n");
      out.write("\t\t heads = headAll.split(\"#\");\r\n");
      out.write("\t\t var contents = new Array();\r\n");
      out.write("\t\t contents = contentAll.split(\"#\");\r\n");
      out.write("\t     \r\n");
      out.write("\t     for(var i=0;i<heads.length;i++){\r\n");
      out.write("\t    \t if ( contents[i] == \"\" )\r\n");
      out.write("\t    \t\t continue;\r\n");
      out.write("\t\t     var tr = $(\"<tr></tr>\");\r\n");
      out.write("\t\t     tr.appendTo($(table));\r\n");
      out.write("\t\t     tr.append(\"<td>\"+heads[i]+\"</td>\").append(\"<td>\"+contents[i]+\"</td>\");\r\n");
      out.write("\t\t     tr.animate({height:'-=40',opacity:'0.0'},0);\r\n");
      out.write("\t\t     tr.animate({opacity:'0.0'},i*aniTime/2);\r\n");
      out.write("\t\t     tr.animate({height:'+=40',opacity:'1.0'},aniTime);\r\n");
      out.write("\t     }\r\n");
      out.write("\t     \r\n");
      out.write("\t     \r\n");
      out.write("\t     $(div).append(\"</table>\");\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction AddItem( head , context )\r\n");
      out.write("\t{\r\n");
      out.write("\t    /* var tr = $(\"<tr></tr>\");\r\n");
      out.write("\t     tr.appendTo($(\"#info-table\"));\r\n");
      out.write("\t     tr.append(\"<td>\"+head+\"</td>\").append(\"<td>\"+context+\"</td>\");\r\n");
      out.write("\t     tr.animate({height:'-=40',opacity:'0.0'},0);\r\n");
      out.write("\t     tr.animate({opacity:'0.0'},i*aniTime/2);\r\n");
      out.write("\t     tr.animate({height:'+=40',opacity:'1.0'},aniTime);*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t//CreateTable(\"div#context\");\r\n");
      out.write("\t\t//CreateUserInfoTable(\"div#context\");\r\n");
      out.write("\t\t$(\"div#menu ul li\").hover(function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'+=25px'}, 500);\r\n");
      out.write("\t\t}, function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'-=25px'},500);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  >\r\n");
      out.write("    \r\n");
      out.write("    <!-- BackGround -->\r\n");
      out.write("    <div  style=\"width:100%;height:100%;position:fixed;z-index:-1;top:0px;left:0px;\">\r\n");
      out.write("\t\t<img src=\"../bgp.jpg\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("\t</div> \r\n");
      out.write("    <!-- *********  Header  ********** -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"header_in\">\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"menu\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a href=\"../man/index.jsp\" >Home</a></li>\r\n");
      out.write("            <li><a href=\"../man/info.jsp\" class=\"active\">Information</a></li>\r\n");
      out.write("            <li><a href=\"../man/record.jsp\">Record</a></li>\r\n");
      out.write("            <li><a href=\"../man/show.jsp\" >Show</a></li>          \r\n");
      out.write("         </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"context\" class = \"info\">\r\n");
      out.write("    \t<div id = \"manage\">\r\n");
      out.write("\t\t\t<input type = \"button\" name = \"update\" value = \"Update\" id = \"updatebtn\" >\r\n");
      out.write("\t\t\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<br>\r\n");
      out.write("    \t");
      //  s:form
      org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
      _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fform_005f0.setParent(null);
      // /man/infoUpdate.jsp(492,5) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setAction("/InfoUpdate");
      // /man/infoUpdate.jsp(492,5) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setMethod("post");
      // /man/infoUpdate.jsp(492,5) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setId("form-info");
      // /man/infoUpdate.jsp(492,5) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setTheme("simple");
      int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_s_005fform_005f0.doInitBody();
        }
        do {
          out.write("\t\t    \r\n");
          out.write("\t\t\t<label>Username *</label>\r\n");
          out.write("\t\t\t<label>");
          out.print(userName );
          out.write("</label>\r\n");
          out.write("\t\t\t<br>\r\n");
          out.write("\t\t\t<label> </label>\r\n");
          out.write("\t\t\t<br>\r\n");
          out.write("\t\t\t<label>Old Password :</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005fpassword_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t<label>New Password :</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005fpassword_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t<label>Confirm New Password</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005fpassword_005f2(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t<label>sex</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005ftextfield_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t<label>age</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005ftextfield_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t<label>Real Name</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005ftextfield_005f2(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t<label>email</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005ftextfield_005f3(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t<label>hobby</label>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005ftextfield_005f4(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_s_005fsubmit_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.reuse(_jspx_th_s_005fform_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.reuse(_jspx_th_s_005fform_005f0);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f0 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    _jspx_th_s_005fpassword_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(499,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setName("oldPassword");
    // /man/infoUpdate.jsp(499,3) null
    _jspx_th_s_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "if you want to change your password");
    int _jspx_eval_s_005fpassword_005f0 = _jspx_th_s_005fpassword_005f0.doStartTag();
    if (_jspx_th_s_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fpassword_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f1 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    _jspx_th_s_005fpassword_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpassword_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(501,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f1.setName("newPassword");
    // /man/infoUpdate.jsp(501,3) null
    _jspx_th_s_005fpassword_005f1.setDynamicAttribute(null, "placeholder", "write your new password here");
    int _jspx_eval_s_005fpassword_005f1 = _jspx_th_s_005fpassword_005f1.doStartTag();
    if (_jspx_th_s_005fpassword_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fpassword_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f2 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    _jspx_th_s_005fpassword_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpassword_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(503,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f2.setName("confirmNewPassword");
    // /man/infoUpdate.jsp(503,3) null
    _jspx_th_s_005fpassword_005f2.setDynamicAttribute(null, "placeholder", "write your password again");
    int _jspx_eval_s_005fpassword_005f2 = _jspx_th_s_005fpassword_005f2.doStartTag();
    if (_jspx_th_s_005fpassword_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f0 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(505,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setName("sex");
    // /man/infoUpdate.jsp(505,3) null
    _jspx_th_s_005ftextfield_005f0.setDynamicAttribute(null, "placeholder", "your sex here");
    int _jspx_eval_s_005ftextfield_005f0 = _jspx_th_s_005ftextfield_005f0.doStartTag();
    if (_jspx_th_s_005ftextfield_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f1 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(507,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setName("age");
    // /man/infoUpdate.jsp(507,3) null
    _jspx_th_s_005ftextfield_005f1.setDynamicAttribute(null, "placeholder", "your age here");
    int _jspx_eval_s_005ftextfield_005f1 = _jspx_th_s_005ftextfield_005f1.doStartTag();
    if (_jspx_th_s_005ftextfield_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f2 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(509,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f2.setName("realName");
    // /man/infoUpdate.jsp(509,3) null
    _jspx_th_s_005ftextfield_005f2.setDynamicAttribute(null, "placeholder", "Please write your real name");
    int _jspx_eval_s_005ftextfield_005f2 = _jspx_th_s_005ftextfield_005f2.doStartTag();
    if (_jspx_th_s_005ftextfield_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f3 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(511,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f3.setName("email");
    // /man/infoUpdate.jsp(511,3) null
    _jspx_th_s_005ftextfield_005f3.setDynamicAttribute(null, "placeholder", "your email here");
    int _jspx_eval_s_005ftextfield_005f3 = _jspx_th_s_005ftextfield_005f3.doStartTag();
    if (_jspx_th_s_005ftextfield_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f3);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f4 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/infoUpdate.jsp(513,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f4.setName("hobby");
    // /man/infoUpdate.jsp(513,3) null
    _jspx_th_s_005ftextfield_005f4.setDynamicAttribute(null, "placeholder", "any hobby?");
    int _jspx_eval_s_005ftextfield_005f4 = _jspx_th_s_005ftextfield_005f4.doStartTag();
    if (_jspx_th_s_005ftextfield_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f4);
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f0 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    _jspx_th_s_005fsubmit_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    int _jspx_eval_s_005fsubmit_005f0 = _jspx_th_s_005fsubmit_005f0.doStartTag();
    if (_jspx_th_s_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
    return false;
  }
}
