/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-19 06:24:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.man;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.UserInfo;
import com.UserInfoUtil;
import com.man.UserInfoShowDAO;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fenctype_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fenctype_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fenctype_005faction.release();
    _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Information</title>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t#menu {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: -20px;\r\n");
      out.write("\tfont-size: 115%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li {\r\n");
      out.write("\t/*float: left;*/\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #101115;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 29px 40px 0 40px;\r\n");
      out.write("\theight: 46px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tfilter:alpha(opacity=50); \r\n");
      out.write("\t-moz-opacity:0.5; \r\n");
      out.write("\topacity:0.5;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a:hover {\r\n");
      out.write("\tbackground-color: #f3f3f3;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #menu ul li a.active {\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tcolor: rgb(200,200,245);\r\n");
      out.write("\tfilter:alpha(opacity=90); \r\n");
      out.write("\t-moz-opacity:0.9; \r\n");
      out.write("\topacity:0.9;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #context {\r\n");
      out.write("\tfont-family:Georgia, serif;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tleft: 300px;\r\n");
      out.write("\tbuttom: 200px;\r\n");
      out.write("\tright: 100px;\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #gravatar{\r\n");
      out.write("\t\tfont-family:Georgia, serif;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: 50px;\r\n");
      out.write("\t\tleft: 750px;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tfont-size: 100%;\r\n");
      out.write("\t\t/*background: url('img/menu_cut.jpg') no-repeat scroll right;*/\r\n");
      out.write("\t\tmargin-right: 0px;\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tborder-style: solid;\r\n");
      out.write(" \t\tborder-color: rgba(255,255,255,0.22);\r\n");
      out.write("  \t\tborder-width: 5px;\r\n");
      out.write("  \t\tborder-radius: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\t/*info table------------------------------------------------------------*/\r\n");
      out.write("\t.info-table\r\n");
      out.write("\t{\r\n");
      out.write("\t  width: 500px;\r\n");
      out.write("\t  float:left;\r\n");
      out.write("\t  margin: 0 auto;\r\n");
      out.write("\t  border-collapse: separate;\r\n");
      out.write("\t  border-spacing: 0;\r\n");
      out.write("\t  text-shadow: 0 1px 0 #fff;\r\n");
      out.write("\t  color: rgba(50,50,50,1.0);\r\n");
      out.write("\t  background: rgba(200,200,200,0.8);\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table td\r\n");
      out.write("\t{\r\n");
      out.write("\t  height: 40px;\r\n");
      out.write("\t  line-height: 40px;\r\n");
      out.write("\t  padding: 0 20px;\r\n");
      out.write("\t  border-bottom: 1px solid #cdcdcd;\r\n");
      out.write("\t  box-shadow: 0 1px 0 white;\r\n");
      out.write("\t  -moz-box-shadow: 0 1px 0 white;\r\n");
      out.write("\t  -webkit-box-shadow: 0 1px 0 white;\r\n");
      out.write("\t  white-space: nowrap;\r\n");
      out.write("\t  text-align: center;\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*Body*/\r\n");
      out.write("\t.info-table tbody td\r\n");
      out.write("\t{\r\n");
      out.write("\t  text-align: center;\r\n");
      out.write("\t  font: normal 20px Georgia , Verdana, Arial, Helvetica;\r\n");
      out.write("\t  width: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table td:nth-child(1)\r\n");
      out.write("\t{\r\n");
      out.write("\t  background: rgba(150,150,150,0);\r\n");
      out.write("\t  width: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table td:nth-child(2)\r\n");
      out.write("\t{\r\n");
      out.write("\t  background: #e7f3d4;\r\n");
      out.write("\t  background: rgba(225,225,225,0.35);\r\n");
      out.write("\t  width: 150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table tr:nth-child(even){\r\n");
      out.write("\t  \tbackground: rgba(255,220,220,0.5);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table tr:nth-child(odd){\r\n");
      out.write("\t  \tbackground: rgba(220,220,255,0.5);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info-table tr:hover\r\n");
      out.write("\t{\r\n");
      out.write("\t  background: rgba(255,255,255,0.3);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* manage button ----------------------------------------------------------------------*/\r\n");
      out.write("    .info #manage input[type=button],\r\n");
      out.write("    .info #manage #choose,\r\n");
      out.write("    .info #manage #submit,\r\n");
      out.write("    .info #manage input[type=file]{\r\n");
      out.write("    /* Width and position */\r\n");
      out.write("    width: 180px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    padding: 4px 2px;\r\n");
      out.write("    margin: 5px 5px 0px 0px ;\r\n");
      out.write("    \r\n");
      out.write("    /* Styles */\r\n");
      out.write("    border: 1px solid #0273dd; /* Fallback */\r\n");
      out.write("    border: 1px solid rgba(0,0,0,0.4);\r\n");
      out.write("    box-shadow:\r\n");
      out.write("        inset 0 1px 0 rgba(255,255,255,0.3),\r\n");
      out.write("        inset 0 10px 10px rgba(255,255,255,0.1);\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    background: rgba(100,100,255,0.5);\r\n");
      out.write("  \r\n");
      out.write("    /* Font styles */\r\n");
      out.write("    font-family: 'trebuchet MS', 'Lucida Sans', Arial;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: 200;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    text-shadow: 0 -1px 0 rgba(100,100,100,0.5);\r\n");
      out.write("\t}\r\n");
      out.write("\t.info #manage #choose{\r\n");
      out.write("   \t\tpadding: 5px 0px 0px 20px;\r\n");
      out.write("   \t\theight:35px;\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\twidth:160px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info #manage input[type=file]{\r\n");
      out.write("\t  width:200px;\r\n");
      out.write("  \t  opacity: 0;\r\n");
      out.write("   \t -moz-opacity: 0;  \r\n");
      out.write("   \t filter: alpha(opacity=0); \r\n");
      out.write("\t}\r\n");
      out.write("\t.info #manage input[type=button]:hover,\r\n");
      out.write("    .info #manage #submit:hover,\r\n");
      out.write("\t.info #manage #text:hover { \r\n");
      out.write("\t    box-shadow: inset 0 1px 0 rgba(255,255,255,0.6);\r\n");
      out.write("\t}\r\n");
      out.write("\t/* end manage button ---------------------------------------------------------*/   \r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

		String userName = (String)session.getAttribute("USER_NAME");
		String head ="";
		String content="";
		
		if ( userName == null || userName == "" )
		{
			
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\twindow.location.href=\"../login/Error.jsp\"; \r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t");
 
		}else{
			UserInfoUtil userInfoUtil = new UserInfoUtil();
			UserInfo userInfo = userInfoUtil.getUserInfo(userName);
			UserInfoShowDAO userInfoShowDAO = new UserInfoShowDAO();
			userInfoShowDAO.setUserInfo(userInfo);
			while( userInfoShowDAO.hasNext()){
				head += userInfoShowDAO.getHead()+"#";
				content += userInfoShowDAO.getContent()+"#";
			}
		}
		
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction CreateTable(div)\r\n");
      out.write("\t  { \r\n");
      out.write("\t   var table=$(\"<table class = \\\"info-table\\\">\");\r\n");
      out.write("\t     table.appendTo($(div));\r\n");
      out.write("\t     var infos = ['Name','Email','Tel','Address','Birthday'];\r\n");
      out.write("\t     var infoNum = 5;\r\n");
      out.write("\t     var aniTime = 300;\r\n");
      out.write("\t     \r\n");
      out.write("\t     var headAll = \"");
      out.print(head);
      out.write("\";\r\n");
      out.write("\t\t var contentAll = \"");
      out.print(content);
      out.write("\";\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var heads = new Array();\r\n");
      out.write("\t\t heads = headAll.split(\"#\");\r\n");
      out.write("\t\t var contents = new Array();\r\n");
      out.write("\t\t contents = contentAll.split(\"#\");\r\n");
      out.write("\t     \r\n");
      out.write("\t     for(var i=0;i<heads.length;i++){\r\n");
      out.write("\t    \t if ( contents[i] == \"\" )\r\n");
      out.write("\t    \t\t continue;\r\n");
      out.write("\t\t     var tr = $(\"<tr></tr>\");\r\n");
      out.write("\t\t     tr.appendTo($(table));\r\n");
      out.write("\t\t     tr.append(\"<td>\"+heads[i]+\"</td>\").append(\"<td>\"+contents[i]+\"</td>\");\r\n");
      out.write("\t\t     tr.animate({height:'-=40',opacity:'0.0'},0);\r\n");
      out.write("\t\t     tr.animate({opacity:'0.0'},i*aniTime/2);\r\n");
      out.write("\t\t     tr.animate({height:'+=40',opacity:'1.0'},aniTime);\r\n");
      out.write("\t     }\r\n");
      out.write("\t     \r\n");
      out.write("\t     \r\n");
      out.write("\t     $(div).append(\"</table>\");\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction AddItem( head , context )\r\n");
      out.write("\t{\r\n");
      out.write("\t    /* var tr = $(\"<tr></tr>\");\r\n");
      out.write("\t     tr.appendTo($(\"#info-table\"));\r\n");
      out.write("\t     tr.append(\"<td>\"+head+\"</td>\").append(\"<td>\"+context+\"</td>\");\r\n");
      out.write("\t     tr.animate({height:'-=40',opacity:'0.0'},0);\r\n");
      out.write("\t     tr.animate({opacity:'0.0'},i*aniTime/2);\r\n");
      out.write("\t     tr.animate({height:'+=40',opacity:'1.0'},aniTime);*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tCreateTable(\"div#context\");\r\n");
      out.write("\t\t//CreateUserInfoTable(\"div#context\");\r\n");
      out.write("\t\t$(\"div#menu ul li\").hover(function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'+=25px'}, 500);\r\n");
      out.write("\t\t}, function(){\r\n");
      out.write("\t\t\t$(this).animate({left:'-=25px'},500);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  >\r\n");
      out.write("    \r\n");
      out.write("    <!-- BackGround -->\r\n");
      out.write("    <div  style=\"width:100%;height:100%;position:fixed;z-index:-1;top:0px;left:0px;\">\r\n");
      out.write("\t\t<img src=\"../bgp.jpg\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("\t</div> \r\n");
      out.write("    <!-- *********  Header  ********** -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"header_in\">\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"menu\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a href=\"../man/index.jsp\" >Home</a></li>\r\n");
      out.write("            <li><a href=\"../man/info.jsp\" class=\"active\">Information</a></li>\r\n");
      out.write("            <li><a href=\"../man/record.jsp\">Record</a></li>\r\n");
      out.write("            <li><a href=\"../man/show.jsp\" >Show</a></li>         \r\n");
      out.write("         </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"context\" class = \"info\">\r\n");
      out.write("    \t<div id = \"manage\" >\r\n");
      out.write("    \t\t<a href=\"../man/infoUpdate.jsp\" >\r\n");
      out.write("\t\t\t<input type = \"button\" name = \"update\" value = \"Update\" id = \"updatebtn\" >\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_s_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("    \t\r\n");
      out.write("    \t<table id=\"info-table\" class=\"info-table\">\r\n");
      out.write("    \t</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div  id = \"gravatar\" >\r\n");
      out.write("    \t<img src=\"../image/gravatar/");
      out.print(userName );
      out.write(".jpg\"  width=\"100%\" height=\"100%\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div  id = \"gravatar\" >\r\n");
      out.write("    \t<img src=\"../image/gravatar/");
      out.print(userName );
      out.write(".png\"  width=\"100%\" height=\"100%\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fenctype_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fform_005f0.setParent(null);
    // /man/info.jsp(313,3) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setAction("/UploadGravatar");
    // /man/info.jsp(313,3) name = enctype type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setEnctype("multipart/form-data");
    // /man/info.jsp(313,3) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setMethod("post");
    // /man/info.jsp(313,3) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setTheme("simple");
    int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
    if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fform_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("    \t\t\t<div id=\"choose\">Choose Gravatar</div>\r\n");
        out.write("    \t\t\t");
        if (_jspx_meth_s_005ffile_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    \t\t\t");
        if (_jspx_meth_s_005fsubmit_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    \t\t");
        int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fenctype_005faction.reuse(_jspx_th_s_005fform_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fenctype_005faction.reuse(_jspx_th_s_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ffile_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:file
    org.apache.struts2.views.jsp.ui.FileTag _jspx_th_s_005ffile_005f0 = (org.apache.struts2.views.jsp.ui.FileTag) _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.FileTag.class);
    _jspx_th_s_005ffile_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ffile_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/info.jsp(315,7) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ffile_005f0.setName("uploadFile");
    int _jspx_eval_s_005ffile_005f0 = _jspx_th_s_005ffile_005f0.doStartTag();
    if (_jspx_th_s_005ffile_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fnobody.reuse(_jspx_th_s_005ffile_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fnobody.reuse(_jspx_th_s_005ffile_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f0 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fid_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    _jspx_th_s_005fsubmit_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /man/info.jsp(316,7) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setId("submit");
    // /man/info.jsp(316,7) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setValue("Upload");
    int _jspx_eval_s_005fsubmit_005f0 = _jspx_th_s_005fsubmit_005f0.doStartTag();
    if (_jspx_th_s_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fid_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fid_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /man/info.jsp(319,5) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("fileName");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
