/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-18 13:45:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("    <head><title>JJJ Login</title>\r\n");
      out.write("        <meta name=\"author\" content=\"AtwoodDeng\" />\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"../favicon.ico\"> \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("\t\t<script src=\"js/modernizr.custom.63321.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery2.js\"></script>\r\n");
      out.write("\t\t<!--[if lte IE 7]><style>.main{display:none;} .support-note .note-ie{display:block;}</style>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t@import url(http://fonts.googleapis.com/css?family=Ubuntu:400,700);\r\n");
      out.write("\t\t\tbody {\r\n");
      out.write("\t\t\t\tbackground: #563c55 url(images/blurred.jpg) no-repeat center top;\r\n");
      out.write("\t\t\t\t-webkit-background-size: cover;\r\n");
      out.write("\t\t\t\t-moz-background-size: cover;\r\n");
      out.write("\t\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.container > header h1,\r\n");
      out.write("\t\t\t.container > header h2 {\r\n");
      out.write("\t\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\t\ttext-shadow: 0 1px 1px rgba(0,0,0,0.7);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsection{\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.form-add input[type=submit] {\r\n");
      out.write("\t\t\t    /* Width and position */\r\n");
      out.write("\t\t\t    width: auto;\r\n");
      out.write("\t\t\t    height: auto;\r\n");
      out.write("\t\t\t    padding: 20px 20px;\r\n");
      out.write("    \t\t\tposition: relative;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t    /* Styles */\r\n");
      out.write("\t\t\t    border: 2px solid #0273dd; /* Fallback */\r\n");
      out.write("\t\t\t    border: 2px solid rgba(0,0,0,0.4);\r\n");
      out.write("\t\t\t    box-shadow:\r\n");
      out.write("\t\t\t        inset 0 3px 0 rgba(255,255,255,0.3),\r\n");
      out.write("\t\t\t        inset 0 20px 20px rgba(255,255,255,0.1);\r\n");
      out.write("\t\t\t    border-radius: 12px;\r\n");
      out.write("\t\t\t    background: #28b6c0;\r\n");
      out.write("\t\t\t    cursor:pointer;\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t    /* Font styles */\r\n");
      out.write("\t\t\t    font-family: 'Ubuntu', 'Lato', sans-serif;\r\n");
      out.write("\t\t\t    color: white;\r\n");
      out.write("\t\t\t    font-weight: 700;\r\n");
      out.write("\t\t\t    font-size: 45px;\r\n");
      out.write("\t\t\t    text-shadow: 0 -1px 0 rgba(0,0,0,0.8);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.form-add input[type=submit]:hover { \r\n");
      out.write("\t\t\t    box-shadow: inset 0 1px 0 rgba(255,255,255,0.6);\r\n");
      out.write("\t\t\t    background: #28b6c0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.form-add input[type=submit]:active { \r\n");
      out.write("\t\t\t    background: #289db5;\r\n");
      out.write("\t\t\t    box-shadow: inset 0 0 3px rgba(0,0,0,0.6);\r\n");
      out.write("\t\t\t    border-color: #000; /* Fallback */\r\n");
      out.write("\t\t\t    border-color: rgba(0,100,100,0.9);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("    </head>\r\n");
      out.write("    ");

    	session.setAttribute("USER_NAME", "");
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<p >\r\n");
      out.write("\t\t\t\t\t<font size = \"15\" face=\"arial\" color=\"white\">Hello, welcome to home of JJJ.</font>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"support-note\">\r\n");
      out.write("\t\t\t\t\t<span class=\"note-ie\">Sorry, only modern browsers.</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<section class=\"main\">\r\n");
      out.write("\t\t\t\t<form class=\"form-3\" method=\"post\" id = \"login\" action=\"judge.jsp\">\r\n");
      out.write("\t\t\t\t    <p class=\"clearfix\">\r\n");
      out.write("\t\t\t\t        <label for=\"login\">Username</label>\r\n");
      out.write("\t\t\t\t        <input type=\"text\" name=\"login\" id=\"login\" placeholder=\"Username\">\r\n");
      out.write("\t\t\t\t    </p>\r\n");
      out.write("\t\t\t\t    <p class=\"clearfix\">\r\n");
      out.write("\t\t\t\t        <label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t\t        <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\"> \r\n");
      out.write("\t\t\t\t    </p>\r\n");
      out.write("\t\t\t\t    <p class=\"clearfix\">\r\n");
      out.write("\t\t\t\t        <input type=\"checkbox\" name=\"remember\" id=\"remember\">\r\n");
      out.write("\t\t\t\t        <label for=\"remember\">Remember me</label>\r\n");
      out.write("\t\t\t\t    </p>\r\n");
      out.write("\t\t\t\t    <p class=\"clearfix\">\r\n");
      out.write("\t\t\t\t        <input type=\"submit\" name=\"submit\" value=\"Sign in\">\r\n");
      out.write("\t\t\t\t    </p>       \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<section class=\"new\"  >\r\n");
      out.write("\t\t\t\t<form class=\"form-add\" id= \"new\" method= \"post\"  action = \"register.jsp\">\r\n");
      out.write("\t\t\t\t    <p class=\"clearfix\">\r\n");
      out.write("\t\t\t\t        <input type=\"submit\" name=\"submit\" value=\"Join Us!\">\r\n");
      out.write("\t\t\t\t    </p>       \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
