/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-18 13:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Register</title>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery2.js\"></script>\r\n");
      out.write("   <!-- <link rel=\"stylesheet\" href=\"reset.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styl.css\" type=\"text/css\"> --> \r\n");
      out.write("        \r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<style type=\"text/css\">  \r\n");
      out.write("\t\r\n");
      out.write("\t.head{\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook',Georgia, 'New York', serif;\r\n");
      out.write("\t    font-weight: 200;\r\n");
      out.write("\t    margin: 0px auto;\r\n");
      out.write("\t    width:350px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg {\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook',Georgia, 'New York', serif;\r\n");
      out.write("\t    font-weight: 200;\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    width: 425px ;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    margin: 60px auto 30px;\r\n");
      out.write("\t    padding: 10px;\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: #222; \r\n");
      out.write("\t    border-radius: 0.4em;\r\n");
      out.write("\t    border: 1px solid #191919;\r\n");
      out.write("\t    box-shadow: \r\n");
      out.write("\t        inset 0 0 2px 1px rgba(255,255,255,0.08), \r\n");
      out.write("\t        0 16px 10px -8px rgba(0, 0, 0, 0.6);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg label {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    width: 40%;\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    padding-top: 9px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    color: #ddd;\r\n");
      out.write("\t    font-size: 12px;\r\n");
      out.write("\t    text-transform: uppercase;\r\n");
      out.write("\t    letter-spacing: 1px;\r\n");
      out.write("\t    text-shadow: 0 1px 0 #000;\r\n");
      out.write("\t    text-indent: 10px;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t    cursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg input[type=text],\r\n");
      out.write("\t#form-reg input[type=password] {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    width: 50%;\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    padding: 8px 5px;\r\n");
      out.write("\t    margin-bottom: 10px;\r\n");
      out.write("\t    font-size: 12px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: #1f2124; /* Fallback */\r\n");
      out.write("\t    background: -moz-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: -ms-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: -o-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: -webkit-gradient(linear, 0 0, 0 100%, from(#1f2124), to(#27292c));\r\n");
      out.write("\t    background: -webkit-linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\t    background: linear-gradient(#1f2124, #27292c);    \r\n");
      out.write("\t    border: 1px solid #000;\r\n");
      out.write("\t    box-shadow:\r\n");
      out.write("\t        0 1px 0 rgba(255,255,255,0.1);\r\n");
      out.write("\t    border-radius: 3px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Font styles */\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook',Georgia, 'New York', serif;\r\n");
      out.write("\t    color: #fff;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg input[type=text]:hover,\r\n");
      out.write("\t#form-reg input[type=password]:hover {\r\n");
      out.write("\t    background: #27292c;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg input[type=text]:focus, \r\n");
      out.write("\t#form-reg input[type=password]:focus {\r\n");
      out.write("\t    box-shadow: inset 0 0 2px #000;\r\n");
      out.write("\t    background: #494d54;\r\n");
      out.write("\t    border-color: #51cbee;\r\n");
      out.write("\t    outline: none; /* Remove Chrome outline */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*#form-reg p:nth-child(3),\r\n");
      out.write("\t#form-reg p:nth-child(4) {\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    width: 200px;\r\n");
      out.write("\t}*/\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg label[for=remember] {\r\n");
      out.write("\t    width: auto;\r\n");
      out.write("\t    float: none;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    text-transform: capitalize;\r\n");
      out.write("\t    font-size: 11px;\r\n");
      out.write("\t    font-weight: 400;\r\n");
      out.write("\t    letter-spacing: 0px;\r\n");
      out.write("\t    text-indent: 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg input[type=checkbox] {\r\n");
      out.write("\t    margin-left: 10px;\r\n");
      out.write("\t    vertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg input[type=submit] {\r\n");
      out.write("\t    /* Width and position */\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height:50px;\r\n");
      out.write("\t    padding: 8px 5px;\r\n");
      out.write("\t    float:right;\r\n");
      out.write("\t    margin:0px auto;\r\n");
      out.write("\t  \r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    border: 1px solid #0273dd; /* Fallback */\r\n");
      out.write("\t    border: 1px solid rgba(0,0,0,0.4);\r\n");
      out.write("\t    box-shadow:\r\n");
      out.write("\t        inset 0 1px 0 rgba(255,255,255,0.3),\r\n");
      out.write("\t        inset 0 10px 10px rgba(255,255,255,0.1);\r\n");
      out.write("\t    border-radius: 3px;\r\n");
      out.write("\t    background: #38a6f0;\r\n");
      out.write("\t    cursor:pointer;\r\n");
      out.write("\t  \r\n");
      out.write("\t    /* Font styles */\r\n");
      out.write("\t    font-family: Times, TimesNR, 'New Century Schoolbook', Georgia, 'New York', serif;\r\n");
      out.write("\t    color: white;\r\n");
      out.write("\t    font-weight: 700;\r\n");
      out.write("\t    font-size: 15px;\r\n");
      out.write("\t    text-shadow: 0 -1px 0 rgba(0,0,0,0.8);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg input[type=submit]:hover { \r\n");
      out.write("\t    box-shadow: inset 0 1px 0 rgba(255,255,255,0.6);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg input[type=submit]:active { \r\n");
      out.write("\t    background: #287db5;\r\n");
      out.write("\t    box-shadow: inset 0 0 3px rgba(0,0,0,0.6);\r\n");
      out.write("\t    border-color: #000; /* Fallback */\r\n");
      out.write("\t    border-color: rgba(0,0,0,0.9);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.no-boxshadow #form-reg input[type=submit]:hover {\r\n");
      out.write("\t    background: #2a92d8;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg:after {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content: \"\";\r\n");
      out.write("\t    height: 1px;\r\n");
      out.write("\t    width: 33%;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 20%;\r\n");
      out.write("\t    top: 0;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    background: -moz-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -ms-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -o-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: -webkit-gradient(linear, 0 0, 100% 0, from(transparent), color-stop(0.25, #444), color-stop(0.5, #b6b6b8), color-stop(0.75, #444), to(transparent));\r\n");
      out.write("\t    background: -webkit-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t    background: linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg:before {\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content: \"\";\r\n");
      out.write("\t    width: 8px;\r\n");
      out.write("\t    height: 5px;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 34%;\r\n");
      out.write("\t    top: -7px;\r\n");
      out.write("\t    \r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    border-radius: 50%;\r\n");
      out.write("\t    box-shadow: 0 0 6px 4px #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-reg p:nth-child(1):before{\r\n");
      out.write("\t    /* Size and position */\r\n");
      out.write("\t    content:\"\";\r\n");
      out.write("\t    width:250px;\r\n");
      out.write("\t    height:100px;\r\n");
      out.write("\t    position:absolute;\r\n");
      out.write("\t    top:0;\r\n");
      out.write("\t    left:45px;\r\n");
      out.write("\t\r\n");
      out.write("\t    /* Styles */\r\n");
      out.write("\t    -webkit-transform: rotate(75deg);\r\n");
      out.write("\t    -moz-transform: rotate(75deg);\r\n");
      out.write("\t    -ms-transform: rotate(75deg);\r\n");
      out.write("\t    -o-transform: rotate(75deg);\r\n");
      out.write("\t    transform: rotate(75deg);\r\n");
      out.write("\t    background: -moz-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: -ms-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: -o-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: -webkit-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    background: linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));\r\n");
      out.write("\t    pointer-events:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"p.clearfix\")\r\n");
      out.write("\t\t.animate({opacity:0},i*250)\r\n");
      out.write("\t\t.animate({opacity:1},500);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  >\r\n");
      out.write("    \r\n");
      out.write("    <!-- BackGround -->\r\n");
      out.write("    <div  style=\"width:100%;height:100%;position:fixed;z-index:-1;top:0px;left:0px;\">\r\n");
      out.write("\t\t<img src=\"images/blurred.jpg\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("\t</div> \r\n");
      out.write("    <!-- *********  Header  ********** -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \t<div class=\"head\">\r\n");
      out.write("    \t\t<font size = \"15\" face=\"arial\" color=\"white\">Join us now!</font>\r\n");
      out.write("    \t</div>\r\n");
      out.write("   \t\t <section class=\"main\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_s_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("    \t\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fform_005f0.setParent(null);
    // /login/register.jsp(252,4) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setAction("/Register");
    // /login/register.jsp(252,4) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setMethod("post");
    // /login/register.jsp(252,4) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setId("form-reg");
    // /login/register.jsp(252,4) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setTheme("simple");
    int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
    if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fform_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t    \r\n");
        out.write("\t\t\t\t    <label>Username *</label>\r\n");
        out.write("    \t\t\t\t");
        if (_jspx_meth_s_005ftextfield_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t    <label >Password *</label>\r\n");
        out.write("   \t\t\t\t\t");
        if (_jspx_meth_s_005fpassword_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t    <label >Confirm *</label>\r\n");
        out.write("   \t\t\t\t\t");
        if (_jspx_meth_s_005fpassword_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("   \t\t\t\t\t\r\n");
        out.write("   \t\t\t\t\t");
        if (_jspx_meth_s_005fsubmit_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.reuse(_jspx_th_s_005fform_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fmethod_005fid_005faction.reuse(_jspx_th_s_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f0 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /login/register.jsp(255,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setName("userName");
    // /login/register.jsp(255,8) null
    _jspx_th_s_005ftextfield_005f0.setDynamicAttribute(null, "placeholder", "your email address is advised.");
    int _jspx_eval_s_005ftextfield_005f0 = _jspx_th_s_005ftextfield_005f0.doStartTag();
    if (_jspx_th_s_005ftextfield_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f0 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    _jspx_th_s_005fpassword_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /login/register.jsp(257,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setName("password");
    // /login/register.jsp(257,8) null
    _jspx_th_s_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "your password here");
    int _jspx_eval_s_005fpassword_005f0 = _jspx_th_s_005fpassword_005f0.doStartTag();
    if (_jspx_th_s_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fpassword_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f1 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    _jspx_th_s_005fpassword_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpassword_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /login/register.jsp(259,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f1.setName("confirmPassword");
    // /login/register.jsp(259,8) null
    _jspx_th_s_005fpassword_005f1.setDynamicAttribute(null, "placeholder", "write your password again");
    int _jspx_eval_s_005fpassword_005f1 = _jspx_th_s_005fpassword_005f1.doStartTag();
    if (_jspx_th_s_005fpassword_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fplaceholder_005fname_005fnobody.reuse(_jspx_th_s_005fpassword_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f0 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    _jspx_th_s_005fsubmit_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    int _jspx_eval_s_005fsubmit_005f0 = _jspx_th_s_005fsubmit_005f0.doStartTag();
    if (_jspx_th_s_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fsubmit_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
    return false;
  }
}
